---
region: eu-west-1
account_number: "070528468658"
hostport: 3000
containerport: 3000
app_name: appname
role: backend
environment: staging
iac: aws-test-applications-eu-west-1-apps-appname
team_name: dev-experience
memory: 1024
cpu: 512
env_vars:
  - name: START_BLOCK
    value: "0"
  - name: NODE_ENV
    value: "staging"
secret_vars:
  - KAFKA_CONNECTION_URL
  - MONGO_URL
  - RPC_WS_ENDPOINT_URL_LIST
  - SENTRY_DSN
