region: eu-west-1
account_number: "058264511034"
hostport: 80
containerport: 80
app_name: static-dev
role: frontend-apps
environment: dev
iac: terraform-workspace-aws-dev-apps-eu-west-1-apps-static-dev-polygon-technology
team_name: product-apps
memory: 1024
cpu: 512
