region: eu-west-1
account_number: "070528468658"
hostport: 3000
containerport: 3000
app_name: static-staging
role: frontend-apps
environment: staging
iac: terraform-workspace-aws-test-applications-eu-west-1-apps-static-staging-polygon-technology
team_name: product-apps
memory: 1024
cpu: 512
