name: Static Deployment
on:
  push:
    branches:
      - dev
      - staging
      - main
    paths:
      - "network/**"
      - ".github/workflows/deployment.yml"
  workflow_dispatch:

jobs:
  set-env-variable:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.set-env-var.outputs.ENVIRONMENT }}
      ACCOUNT_NUMBER: ${{ steps.set-env-var.outputs.ACCOUNT_NUMBER }}
    steps:
      - name: Set Environment Variable
        id: set-env-var
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "::set-output name=ENVIRONMENT::dev"
            echo "::set-output name=ACCOUNT_NUMBER::058264511034"
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "::set-output name=ENVIRONMENT::staging"
            echo "::set-output name=ACCOUNT_NUMBER::070528468658"
          elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "::set-output name=ENVIRONMENT::prod"
            echo "::set-output name=ACCOUNT_NUMBER::042947190491"
          fi

  deploy:
    uses: 0xPolygon/pipelines/.github/workflows/ecs_deploy_docker_taskdef.yaml@main
    needs: set-env-variable
    with:
      app_name: static-${{ needs.set-env-variable.outputs.ENVIRONMENT }}
      taskdef_file_vars: .github/taskdef/${{ needs.set-env-variable.outputs.ENVIRONMENT }}-taskdef.yaml
      account_number: "${{ needs.set-env-variable.outputs.ACCOUNT_NUMBER }}"
      aws_region: eu-west-1
      environment: ${{ needs.set-env-variable.outputs.ENVIRONMENT }}
      docker_file: .github/Dockerfile
      cluster_name: static-${{ needs.set-env-variable.outputs.ENVIRONMENT }}-ecs-cluster
    secrets: inherit
