name: Static Deployment
on:
  push:
    branches:
      - master
      - DEVOPS-2599-cors-issue-update
  workflow_dispatch:
    inputs:
      environment:
        required: false
        type: choice
        description: "Select the environment to deploy to (optional for pushes)"
        options:
          - staging
          - prod

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      environment: "staging"
      # environment: ${{ inputs.environment || 'dev' }}
    secrets: inherit
